version: "3.3"

services:
# nestjs API
  api:
      build:
        dockerfile: Dockerfile
        context: ./api
        # Only build development stage from Dockerfile
        target: development
      # Mount our host dir to the docker container
      # Mount api directory (./api) to (:) docker container (/thomas/src/app)
      # Reflect File changes from host to container
      volumes:
        - ./api:/src/app
        - /src/app/node_modules/
      # RUN in debug mode: npm run start:debug --> Also start vscode debugger
      # Run in dev mode: npm run start:dev
      command: npm run start:debug
      depends_on: 
        - postgres
      environment:
        DATABASE_URL: postgres://user:password@postgres:5432/db
        NODE_ENV: development
        PORT: 3000
      ports:
        - 3000:3000
        - 9229:9229

# Angular frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/frontend/src/app
      - /frontend/src/node_modules/
    ports:
      - 4200:4200
    links:
      - api

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80  

